# Generated by Django 4.2.4 on 2023-09-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_city_store_state_alter_store_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'store', 'verbose_name_plural': 'stores'},
        ),
    ]
